builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    binary: octo
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - name: octo
    github:
      owner: octo-cli
      name: homebrew-octo
    homepage: https://github.com/octo-cli/octo-cli
    folder: HomebrewFormula
    commit_author:
      name: octo-cli bot
      email: octo-cli-bot@local
    description: cli client for GitHub
    skip_upload: auto

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
