required = ["github.com/golangci/golangci-lint/cmd/golangci-lint"]

[[constraint]]
  name = "github.com/alecthomas/kong"
  version = "0.1.9"

[[constraint]]
  name = "github.com/fatih/structtag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[prune]
  go-tests = true
  unused-packages = true
