name: tag-releaser
on:
  push:
    tags:
      - 'v*'
jobs:
  update-routes:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
