name: update-routes
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
jobs:
  update-routes:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.14.0'
      - run: script/update-routes
        env:
          GITHUB_TOKEN: ${ github.token }
